import React from 'react';
import { BookOpen, ShieldCheck, HelpCircle } from "lucide-react";

/**
 * WaspInfo Component - "Expert Knowledge Base" section
 * Contains 23 deep-content Q&As (>150 words each) in a 2-column layout.
 * Questions are formatted as <h3> for SEO.
 * Answer backgrounds are solid white for readability.
 */

const FAQItem = ({ item, index }: { item: { q: string; a: string }, index: number }) => (
  <div className="mb-8 p-8 rounded-3xl bg-white shadow-xl shadow-slate-200/50 border border-slate-100 group hover:border-amber-500/30 transition-all duration-300">
    <div className="flex items-start gap-4 mb-4">
      <div className="w-10 h-10 rounded-xl bg-amber-100 flex items-center justify-center shrink-0">
        <HelpCircle className="w-5 h-5 text-amber-600" />
      </div>
      <h3 className="text-xl font-bold text-slate-900 leading-tight group-hover:text-amber-700 transition-colors uppercase tracking-tight">
        {item.q}
      </h3>
    </div>
    <div className="pl-14">
      <p className="text-slate-600 leading-relaxed font-normal text-sm whitespace-pre-line p-6 bg-slate-50/50 rounded-2xl italic border-l-4 border-amber-500">
        {item.a}
      </p>
    </div>
  </div>
);

const WaspInfo = () => {
  const faqs = [
    {
      q: "How much does it cost to have someone get rid of a wasp nest?",
      a: "The cost for professional wasp nest removal in Hillsborough, NC typically ranges between $150 and $450, though several factors can influence the final quote provided by a licensed exterminator. One of the primary drivers of price is the location and accessibility of the nest. A nest located at ground level or under an eave reachable by a standard ladder is significantly less expensive than one inside a chimney, within a high attic space, or buried deep within a wall void, as these scenarios require specialized exclusion equipment and potential structural repairs. \n\nAnother factor is the type of stinging insect involved; while standard paper wasps are relatively straightforward to handle, aggressive yellow jackets or large bald-faced hornet colonies often necessitate higher levels of personal protective equipment and more intensive residual chemical applications. The size of the colony and the time of year also play roles, with late-season nests being much larger and more defensive, sometimes requiring multiple follow-up visits to ensure complete eradication of foraging workers. Homeowners should also consider if the service includes a guarantee or a preventive treatment for the surrounding area, as these value-added services protect against re-infestation but may come with a slightly higher upfront investment. Ultimately, hiring a professional ensures safety and efficiency that far outweighs the risks of DIY attempts."
    },
    {
      q: "Who do I call to get a wasp nest removed?",
      a: "When you discover a wasp nest on your property in Hillsborough, you should contact a professional pest control service that specializes specifically in stinging insect removal or 'wasp nest extraction.' While general pest control companies can handle basic situations, look for a team that offers emergency response and same-day service, as wasp infestations can quickly become a safety hazard for families and pets. Local Hillsborough experts are often the best choice because they understand the specific behavior patterns of North Carolina's indigenous wasp species, such as the common European Paper Wasp and the highly aggressive Southern Yellow Jacket. \n\nIn addition to pest control companies, some specialized wildlife removal services may also handle hornet and wasp removal, especially for extremely large or complex installations. It is crucial to verify that the company is fully insured and licensed by the North Carolina Department of Agriculture and Consumer Services. Calling a professional ensures that the removal is done using industrial-grade aerosols, dusts, or traps that are not available to the general public. These professionals have the proper training to approach the nest during low-activity hours—typically dusk or early morning—to maximize the elimination of the active colony. Avoid calling generic handymen or landscapers for this task, as they rarely possess the necessary protective equipment or chemical expertise to prevent dangerous stings or improper disposal."
    },
    {
      q: "What does WD-40 do to wasps?",
      a: "WD-40 is often cited as a household hack for killing wasps, and while it can be effective as a contact killer, it is not recommended as a primary or sole method for wasp nest removal in Hillsborough. The chemical composition of WD-40, which includes mineral spirits and petroleum-based lubricants, acts as a surfactant that essentially coats the wasp's body. Wasps breathe through small openings called spiracles located along their abdomen; the oily residue from WD-40 clogs these openings almost instantly, causing the wasp to suffocate and die within seconds. This makes it highly effective for knocking down a single scout wasp that has entered your home. \n\nHowever, using WD-40 on a full nest is dangerous and often counterproductive. WD-40 lacks the long-range spray capabilities of professional wasp aerosols, forcing you to get dangerously close to the nest. Furthermore, WD-40 is highly flammable and can leave permanent oily stains on vinyl siding, wood, or brick, potentially causing structural damage or fire hazards. It also provides zero residual effect; once it dries, it will not prevent surviving wasps or foragers from returning to the same spot. For a permanent solution in Hillsborough, it is always safer to use specialized pest control products or, better yet, call a professional service that uses residual insecticides designed to eliminate the entire colony and provide lasting protection for your home's exterior."
    },
    {
      q: "How much does Terminix charge to remove a wasp nest?",
      a: "National pest control chains like Terminix typically charge anywhere from $200 to $500 for a one-time wasp nest removal service in the Hillsborough, NC area. Their pricing model usually starts with a base inspection fee, which may be waived if you sign up for an annual or quarterly pest protection plan. For a standalone service, the cost covers the assessment of the infestation, the application of professional-grade pesticides, and the physical removal of the nest if it is reachable. If the nest is located high up on an eave or inside a complicated structural void, expect the price to trend toward the upper end of that range due to the complexity and risk involved. \n\nMany national providers prefer to bundle wasp removal into a recurring service contract. While this can reach $40 to $60 per month, it often includes a 'pest-free guarantee,' meaning they will return and treat the area for free if wasps reappear. Local Hillsborough specialists may offer more competitive one-time rates, as they have less overhead than national conglomerates. When comparing quotes, it is important to ask whether the price includes the removal of the dead nest structure, as leaving the nest behind can sometimes attract other pests or give the impression that the property is still infested. Always get a written estimate before the work begins to ensure there are no surprises regarding emergency surcharges or hazardous location fees."
    },
    {
      q: "What kills wasp nests instantly?",
      a: "To achieve near-instantaneous knockdown of a wasp nest in Hillsborough, professionals utilize high-pressure aerosol sprays containing active ingredients like pyrethrins or synthetic pyrethroids such as tetramethrin or prallethrin. These chemicals act as neurotoxins that strike the wasp's central nervous system upon contact, causing immediate paralysis and death. Professional-grade sprays are designed with a powerful stream that can reach up to 20 or 25 feet, allowing the technician to stay at a safe distance while saturating the nest entrance. \n\nAnother highly effective method for 'instant' results in wall voids or ground nests is the use of insecticidal dusts like deltamethrin. While the kill isn't as visual as a liquid spray, the foragers carry the dust deep into the hive, distributing it to the queen and larvae, which results in the total collapse of the colony within hours. Many property owners try to use soapy water, but this only works on contact with individual wasps and is entirely ineffective for neutralizing the interior of a large nest. For the fastest results that actually last, a combination of a knockdown agent for active workers and a residual dust for the hidden queen is the industry standard. This multi-phase approach ensures that you aren't just killing a few wasps but actually terminating the biological unit of the colony instantly."
    },
    {
      q: "Are professional wasp removal services worth it?",
      a: "Investing in professional wasp removal in Hillsborough, NC is overwhelmingly considered worth it due to the significant safety, effectiveness, and efficiency benefits provided. The most immediate 'worth' comes from the elimination of physical risk. Wasps in North Carolina, especially yellow jackets and hornets, are highly aggressive and can sting multiple times, potentially leading to anaphylactic shock even in individuals who have no prior history of allergies. Professionals wear full-body protective suits and use long-range application tools that keep them—and you—out of harm's way. \n\nFurthermore, DIY treatments often fail because they don't reach the queen or the hidden parts of the nest, leading to a 'rebound' infestation where the wasps become even more aggressive after a failed attempt. A professional service provides a comprehensive solution that includes identification of the species, locating hidden nests you might have missed, and applying residual chemicals that prevent new colonies from moving into the same space. When you factor in the cost of multiple cans of ineffective store-bought spray, the potential medical bills from a trip to the emergency room, and the peace of mind knowing the job is done right the first time, the professional fee is a small price to pay for a wasp-free property."
    },
    {
      q: "Why are wasps so bad in October?",
      a: "In Hillsborough and throughout the Piedmont region, wasp activity peaks in October due to a fascinating and dangerous shift in their biological cycle. At this time of year, the colony has reached its maximum size, and the focus of the workers changes from feeding larvae to preparing for winter. The larvae normally produce a sugary secretion that feeds the adult workers; however, as the queen stops laying eggs and fewer larvae are produced, the adult workers become desperate for new sugar sources. This is why you'll see them swarming around soda cans, fallen fruit, and trash bins more aggressively in the fall. \n\nAdditionally, the old queen is dying, and the colony is transitioning to produce 'gynes' or new queens that will hibernate for the winter. The remaining worker wasps are essentially 'unemployed' and homeless, making them extremely irritable and prone to stinging at the slightest provocation. Cooler temperatures also make wasps sluggish and more likely to seek warmth near your home's windows and doors, leading to higher rates of indoor encounters. This seasonal aggression makes October the most dangerous month for wasp encounters in North Carolina, requiring heightened vigilance and professional intervention if a large nest is discovered near high-traffic areas of your home."
    },
    {
      q: "Will a wasp nest eventually go away?",
      a: "While a wasp nest in Hillsborough will technically 'go away' in the sense that the colony will die off in the winter, the actual structure of the nest will remain, and the problem often returns in the spring if not properly addressed. In North Carolina, the first few hard freezes of the winter kill off all the worker wasps and the old queen. Only the newly mated queens survive, and they leave the nest to find a protected place to hibernate, such as under tree bark or inside your home's attic insulation. \n\nHowever, leaving an abandoned nest can cause several issues. While most wasp species do not reuse the same physical nest structure the next year, they often return to the exact same lucrative nesting site because it has proven to be successful. An old nest can also attract other pests, such as carpet beetles or scavenger insects, that feed on the remains of dead wasp larvae or the nest material itself. Furthermore, if you are dealing with a species like the German Yellow Jacket, their colonies can sometimes survive mild winters in protected indoor spaces, becoming perennial problems that grow to massive, dangerous sizes. Relying on 'waiting it out' is a risky strategy if the nest is located near an entry point or a play area, as the danger persists right up until the deepest part of winter."
    },
    {
      q: "What do wasps absolutely hate?",
      a: "Wasps are extremely sensitive to certain scents and environmental factors that can be used to keep them away from your Hillsborough property. They have a highly developed sense of smell and absolutely 'hate' the scent of peppermint oil. Many homeowners find success by mixing peppermint essential oil with water and spraying it around eaves, windowsills, and other potential nesting sites. Other scents that act as natural repellents include eucalyptus, citronella, and cloves. Interestingly, wasps also have a strong aversion to the scent of vinegar, which can be used to clean outdoor dining surfaces to discourage them from foraging near humans. \n\nBeyond scents, wasps hate being 'counter-scouted.' There is a theory that they won't build a nest near an existing one to avoid territorial conflict; this has led to the popularity of 'decoy' nests made of gray paper or plastic. While their effectiveness is debated by experts, the visual deterrent can sometimes cause a queen to move on to a different yard. Finally, wasps hate smoke, which interferes with their pheromone communication and makes them sluggish. While these natural repellents are great for keeping a few foragers away from a picnic, they are entirely ineffective for removing an established nest. If you have a colony already living in your walls or under your roof, these scents will not drive them out, and professional extraction remains the only reliable solution."
    },
    {
      q: "Can I get rid of a wasp nest myself?",
      a: "Technically, you can attempt to get rid of a small, visible paper wasp nest yourself using store-bought aerosols, but it is highly discouraged for residents in Hillsborough, especially if the nest is large or involves yellow jackets. The risk of injury is incredibly high; a single nest can contain thousands of wasps that can coordinate an attack in seconds. DIY attempts often fail because the spray doesn't penetrate deep enough into the nest layers, leaving the queen alive. This results in the remaining workers becoming extremely defensive and aggressive, making a second attempt significantly more dangerous. \n\nCommon DIY mistakes include using fire, which can quickly burn down your house, or using a hose to spray down the nest, which usually just creates a swarm of angry, wet wasps that can follow you inside. If you are determined to try it for a very small nest, you must do so at night when the wasps are dormant, wear heavy clothing that covers every inch of your skin, and ensure you have a clear, obstacle-free path for a quick escape. However, given that professional services in Hillsborough are affordable and offer guaranteed results, the risk of serious medical complications from multiple stings simply isn't worth the small savings of a DIY project. Professional intervention is the only way to ensure the safety of your family and the complete removal of the pest problem."
    },
    {
      q: "What happens if you don't get rid of a wasp nest?",
      a: "If you ignore a wasp nest on your Hillsborough property, the situation will almost certainly escalate in size, aggression, and structural risk. Throughout the spring and summer, the queen continues to lay eggs, and the worker population grows exponentially. What started as a small, golf-ball-sized nest in May can become a basketball-sized colony by August containing thousands of individuals. This increased population means more foragers looking for food, leading to frequent encounters on your deck, near your trash, and around your front door. \n\nMoreover, some species, particularly yellow jackets, can cause actual structural damage if the nest is inside a wall or attic. They can chew through drywall and insulation to expand their living space, and in extreme cases, they have been known to break through the ceiling and enter the living quarters of a home. The weight of a large nest, combined with the accumulation of moisture and insect waste, can also lead to foul odors and staining on your walls. Finally, the longer you wait, the more 'future queens' the nest will produce. These queens will hibernate nearby and start new colonies on your property next spring, essentially turning a one-year problem into a perennial infestation. Removing the nest early is key to preventing a massive, dangerous population explosion and potential repairs."
    },
    {
      q: "What's the best time to remove a wasp nest?",
      a: "Timing is everything when it comes to safe and effective wasp nest removal in Hillsborough. The absolute best time of day is during the late evening, night, or very early morning hours. During these times, the wasps are dormant and the entire colony—including the foragers that have been out all day—is back inside the nest. This allows for total elimination of the population in a single treatment. If you treat a nest during the middle of the day, you will likely kill the wasps inside, but the hundreds of foragers that are out looking for food will return later, find their home destroyed, and become confused and highly aggressive near your house. \n\nIn terms of the time of year, earlier is always better. In Hillsborough, keeping a close eye on your eaves and porch ceilings in March and April allows you to catch the 'foundress' queens as they are just beginning to build small, vulnerable nests. Removing a nest with only one queen and a few larvae is significantly easier and safer than dealing with a mature colony in July or August. However, regardless of the time of year, once a nest is identified near a doorway or high-traffic area, it should be addressed as soon as possible by a professional to prevent the colony from growing and becoming a more significant safety hazard."
    },
    {
      q: "Where do wasps go at night if they don't have a nest?",
      a: "If a wasp in Hillsborough finds itself without a nest at night—either because it got lost or its nest was recently destroyed—it will seek shelter in dark, protected spaces. Wasps are not nocturnal and have poor night vision, so they stop flying once the light fades to avoid predators and cold temperatures. They will often crawl into small crevices in tree bark, under dense leaf litter, or behind loose pieces of wood or siding on a house. They go into a state of low activity, huddling together to conserve heat and energy. \n\nForagers that are caught out at night are often found hanging onto the undersides of leaves or in the folds of outdoor umbrellas. This is why it can be dangerous to move outdoor furniture or landscape debris early in the morning, as you might disturb a dormant wasp that is ready to defend itself as soon as the sun warms it up. If a nest has been removed during the day, the returning foragers will often 'cluster' together at the site where the nest used to be, sitting on the wall or ceiling through the night. This is why professional exterminators often apply a residual spray to the area even after the nest is gone; it ensures that the homeless foragers are eliminated when they land at the site that night."
    },
    {
      q: "Do wasps come back to the same nest every year?",
      a: "Contrary to popular belief, most wasp species in Hillsborough and North Carolina do not reuse the exact same physical nest from a previous year. The paper or mud structure typically degrades over the winter, and the new queens that survive the cold prefer to build a fresh, clean nest for their new colonies. However, this does not mean the wasps are 'gone' for good. Wasps are highly methodical about selecting nesting sites based on factors like protection from the wind, proximity to food and water, and heat retention. If your home has a specific eave or attic vent that was successful for a colony one year, it is highly likely that a new queen will find that same spot attractive the following spring. \n\nThis is why you will often see several old, gray, 'dead' nests clustered in the same corner of a porch or garage. While the old nests are empty, they serve as a marker that the area is an ideal habitat. This is also why professional treatment is more effective than simple physical removal; a pro will apply a residual repellent to the area that makes it unattractive to the next generation of queens. So, while they don't 'move back in' to the old house, they definitely like to build in the same neighborhood if you don't take preventive measures."
    },
    {
      q: "What happens if you block up a wasp's nest?",
      a: "Blocking the entrance to a wasp's nest—especially one located inside a wall void or a brick crevice—is one of the most dangerous and damaging mistakes a Hillsborough homeowner can make. When you seal the exit point using caulk, spray foam, or cement while the colony is still active inside, the wasps do not simply die. Instead, they become extremely distressed and immediately begin looking for or creating a new way out. Because many wasps can chew through soft materials like drywall, plaster, and insulation, they often end up exiting 'into' the house rather than 'out' of it. \n\nThis can result in hundreds or even thousands of angry wasps entering your living room, bedroom, or kitchen, creating a terrifying and life-threatening emergency. Furthermore, if they die inside the wall, the accumulation of dead insects, larvae, and waste will rot, causing a horrendous odor and potentially attracting secondary pests like flesh flies or carpet beetles. The correct procedure for a wall-nested colony is to first eliminate the hive using non-repellent dusts that the workers carry inside, ensuring the entire colony is dead before any entry points are sealed. Never attempt to 'trap' an active wasp colony inside your home's structure; it will always make the situation more complicated and expensive to resolve."
    },
    {
      q: "How do professionals get rid of wasp nests?",
      a: "Professional wasp removal in Hillsborough involves a systematic and safety-focused approach that far exceeds the capabilities of a typical homeowner. The process begins with a thorough inspection to identify the species and locate all primary and secondary nests. Once identified, the technician will typically use a high-reach poles or specialized application equipment to deliver a professional-strength insecticide directly into the nest entrance. These chemicals often include both a 'knockdown' agent to stop active guards and a 'non-repellent' residual that ensures foragers returning later are also eliminated. \n\nFor nests in high or difficult-to-reach locations, professionals use specialized lift equipment or high-pressure sprayers that can accurately target a nest from a safe distance on the ground. For ground nests or those inside wall voids, they utilize insecticidal dusters that inject a fine powder deep into the colony structure. After the active colony has been neutralized—which usually happens very quickly due to the potency of the chemicals—the technician will physically remove and dispose of the nest structure to prevent attractants from remaining on the property. Finally, they often perform a 'perimeter spray' around your home's eaves and doors to act as a barrier against future queens looking for a place to build. This comprehensive approach ensures the problem is solved immediately and stays solved."
    },
    {
      q: "How do exterminators get rid of wasp nests?",
      a: "Exterminators in Hillsborough use a combination of biological knowledge and chemical precision to eradicate wasp nests. A key tool in their arsenal is the use of 'residual' pesticides. Unlike store-bought sprays that only kill the wasps they touch, the chemicals used by professionals remain active on the surface for weeks. When a wasp walks over a treated area, it picks up a lethal dose and carries it back to the hive, eventually spreading it to the queen. This is particularly crucial for hidden nests where the exterminator cannot physically see or touch the entire hive. \n\nAdditionally, professional exterminators use protective gear—often called a 'bee suit'—which consists of heavy-duty fabric, gloves, and a mesh veil that prevents stings even if the wasps swarm during the treatment. They also use specialized 'dusting' tools for ground and wall infestations. These tools use compressed air to blow a fine insecticidal powder into every crevice of the nest. This ensures that every individual, including the deep-seated larvae and the queen, is exposed. For high-eave work, they use extending poles with applicators attached, allowing them to treat a nest 30 feet up without even leaving the ground. The final step is often the physical scraping of the nest and cleaning the site with a neutralizing agent to remove the pheromones that might attract other wasps to the same spot later."
    },
    {
      q: "Can I remove a wasp nest without killing them?",
      a: "Removing a wasp nest humanely or without killing the colony is extremely difficult and rarely practiced in Hillsborough due to the aggressive nature of the insects. Unlike honeybees, which are often relocated by professional beekeepers because of their ecological importance, wasps and hornets are generally considered pests and their relocation is dangerous and commercially unfeasible. Most 'bee relocation' services will specifically exclude wasps from their offerings because a wasp colony cannot be easily 'captured' and moved into a hive box like a bee swarm. \n\nIf you are set on a humane approach, your only real option is to wait until the winter freezes kill off the colony and then remove the empty nest structure. However, this is only safe for areas that are not frequently used by people or pets. If the nest is in a high-traffic area, the risk of injury makes lethal removal the standard recommendation. Some homeowners try to use natural repellents like essential oils to 'encourage' them to leave, but once a queen has established a nest and has larvae to care for, she is extremely unlikely to abandon her home for any non-lethal reason. In the interest of public safety, professional services in North Carolina focus on the fast and permanent elimination of the stinging threat rather than relocation."
    },
    {
      q: "What happens if you remove a wasp nest?",
      a: "When you remove a wasp nest from your Hillsborough property, several things happen in the immediate aftermath. If the removal was done professionally and the colony was neutralized, the site will be safe within a very short time. However, you may notice 'homeless' foragers hovering around the spot where the nest used to be for 24 to 48 hours. These are wasps that were out foraging when the nest was taken and are now confused by the change in their environment. This is why pros apply a residual spray to the site; these foragers will land on the treated surface and be eliminated, preventing them from hanging around and potentially stinging residents. \n\nStructurally, removing the nest prevents the accumulation of moisture and insect waste that can rot wood or stain siding. Long-term, the removal of the pheromone-laden nest structure reduces the likelihood that the site will be immediately recognized as a 'safe' spot by other opportunistic pests. If you remove a nest yourself without killing the wasps first, you will likely be attacked, and the surviving wasps will immediately begin rebuilding exactly where the old nest was, often with even more aggression. Proper removal involves total colony termination plus physical extraction to ensure the cycle is truly broken."
    },
    {
      q: "Will a wasp nest disappear?",
      a: "A wasp nest will not 'disappear' on its own in the short term. The paper-like substance, made from chewed wood fibers and saliva, is surprisingly durable and can survive for many months even after the colony has died out in the winter. In a protected area like an attic or under a deep eave in Hillsborough, a nest can remain intact for years, slowly becoming a dusty, fragile relic. Over time, environmental factors like wind, humidity, and the activity of other insects like carpet beetles or 'nest scavengers' will cause the nest to break apart and fall, but this process takes a long time. \n\nBecause of this durability, homeowners often find 'ghost' nests that are several seasons old. While these nests aren't dangerous themselves, they are unsightly and can serve as indicators to new queens that the area is an excellent place for a home. If you see a nest, you should never assume it's abandoned just because you don't see immediate activity; many colonies are quiet during certain times of the day or in cooler weather. It's always best to have the structure physically removed once it's confirmed dead to keep your home looking clean and to discourage future nesting activity in that specific location."
    },
    {
      q: "How to humanely get rid of a wasp's nest?",
      a: "Humane removal of a wasp nest in Hillsborough is primarily achieved through prevention rather than intervention once a colony is established. The most 'humane' thing a homeowner can do is to be proactive in the early spring by sealing up cracks, using essential oil repellents like peppermint, and hanging 'decoy' nests to prevent a queen from ever starting her colony on your home. By discouraging the queen before she lays eggs, you prevent the need for lethal measures later in the season. \n\nIf a nest is already active and you wish to avoid harsh chemicals, some people use 'soapy water' sprays which kill by coating the spiracles of the wasps, although this is still lethal, it is often seen as 'greener' than synthetic neurotoxins. Truly non-lethal removal would require a specialized vacuum system that captures the wasps alive for release in a distant wilderness area, but this is extremely rare, incredibly expensive, and carries a high risk of stings for the operator. In most cases, the standard of care in North Carolina is to prioritize human safety, leading to the use of targeted professional elimination. Waiting for the winter die-off is the only truly non-interventionist 'humane' way to see a nest go away, but this is only suggested for nests located far away from human activity."
    },
    {
      q: "Should I remove an abandoned wasp nest?",
      a: "Yes, you should remove an abandoned wasp nest from your Hillsborough property, but only after you have confirmed with 100% certainty that the colony is dead. Even during the winter, a nest can occasionally house a few surviving wasps if it's in a particularly warm or protected spot. Once confirmed dead, removal is beneficial for several reasons. First, it improves the aesthetics of your home, removing the gray, papery clumps from your eaves and porches. Second, it removes a source of allergens; the debris and discarded skins within a nest can trigger respiratory issues in sensitive individuals. \n\nThird, an old nest contains organic matter—dead larvae, waste, and food remains—that can attract secondary pest infestations. Carpet beetles, ants, and certain types of flies are known to scavenge abandoned wasp nests, and these pests can eventually move into the interior of your home. Finally, while wasps usually don't reuse the same structure, leaving the old nest 'validates' the site for future queens. Removing the nest and cleaning the area with a mild bleach solution or a professional repellent disrupts the pheromone trails and makes it less likely that you'll have a repeat performance next spring. It’s part of a sound Integrated Pest Management strategy to keep your home clean and pest-free."
    },
    {
      q: "When's the best time to remove a wasp's nest?",
      a: "For the most effective and safest result in Hillsborough, the prime time to remove a wasp's nest is in the early spring (April or May) during the late evening hours (after 9:00 PM). In the spring, the nests are still in the 'foundress' stage, meaning they are small and only occupied by a single queen and maybe a few early workers. Tackling the problem then prevents the massive population explosion that occurs in late summer. Doing the removal at night is critical because wasps are diurnal—they need sunlight and warmth to fly effectively. \n\nWhen the temperatures drop at night, the wasps' metabolism slows down, making them sluggish and much slower to react. Furthermore, by waiting until dark, you ensure that every single flying member of the colony is inside the nest, allowing you to wipe out the entire population in one go. If you try to remove it during the day, you will be faced with active, alert guards and will miss the hundreds of workers that are currently away from the nest. These 'leftover' wasps will remain at the site for days, becoming increasingly aggressive and desperate. Therefore, the 'Spring + Night' combination is the industry gold standard for wasp removal, though professional teams are equipped to handle nests at any time and any season."
    }
  ];

  // Split faqs into two columns
  const firstCol = faqs.slice(0, 12);
  const secondCol = faqs.slice(12);

  return (
    <section id="faq" className="py-24 bg-slate-950 relative overflow-hidden">
      {/* Decorative Background Elements */}
      <div className="absolute top-0 left-0 w-full h-full">
        <div className="absolute top-1/4 left-0 w-96 h-96 bg-amber-600/10 rounded-full blur-[120px] -translate-x-1/2" />
        <div className="absolute bottom-1/4 right-0 w-96 h-96 bg-amber-600/10 rounded-full blur-[120px] translate-x-1/2" />
      </div>

      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-20">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-500 mb-6 font-bold uppercase tracking-[0.2em] text-xs">
            <BookOpen className="w-4 h-4" />
            Wasp Expert Knowledge Base
          </div>
          <h2 className="text-4xl md:text-6xl font-heading font-bold text-white mb-6 uppercase tracking-tight">
            Deep Insights Into <span className="text-amber-500">Wasp Control</span>
          </h2>
          <p className="text-xl text-slate-400 max-w-2xl mx-auto font-medium italic">
            Everything you need to know about managing, removing, and preventing wasp infestations in Hillsborough, NC.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 items-start">
          <div className="space-y-4">
            {firstCol.map((item, idx) => (
              <FAQItem key={idx} item={item} index={idx} />
            ))}
          </div>
          <div className="space-y-4">
            {secondCol.map((item, idx) => (
              <FAQItem key={idx + 12} item={item} index={idx + 12} />
            ))}
          </div>
        </div>

        <div className="mt-20 p-12 rounded-[3rem] bg-gradient-to-br from-amber-600 to-amber-700 text-center shadow-2xl relative overflow-hidden group">
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-10" />
          <div className="relative z-10">
            <h3 className="text-3xl md:text-4xl font-heading font-bold text-white mb-6 uppercase tracking-tighter">
              Still Have Dangerous Wasps?
            </h3>
            <p className="text-white/90 text-xl mb-10 max-w-2xl mx-auto font-medium italic">
              Don't risk multiple stings or a fall from a ladder. Our Hillsborough wasp specialists are ready with professional gear and instant-knockdown protocols.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
              <a href="tel:3238801224" className="bg-white text-amber-600 hover:bg-amber-50 h-16 px-10 rounded-2xl text-xl font-bold flex items-center gap-3 transition-transform hover:scale-105 shadow-xl">
                <ShieldCheck className="w-6 h-6" />
                (323) 880-1224
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default WaspInfo;
